### ISSUE TITLE
Incorrect handling of single metric input for yt_analytics

### ISSUE THREAD

**Issue by gnatamania** [MarkEdmondson1234/youtubeAnalyticsR#1]
when `metrics` in yt_analytics() only has one value, it returns a dataframe with a column for every dimension. eg
```
yt_analytics("<CHANNEL_ID>", 
             start.date = "2016-12-01", end.date = "2016-12-02", 
             metrics = c("views"), dimensions = "day")
```
returns
```
         day X1234 X5678
1 2016-12-01  1234  5678
2 2016-12-02  1234  5678
```
instead of expected
```
         day views 
1 2016-12-01  1234
2 2016-12-02  5678
```

**Comment by MarkEdmondson1234** [comment]
@gnatamania Thanks, I can't test it but I've taken a guess what causes this.  If it doesn't work, I'll take a look next week when I'm near an account I can test with.

**Comment by MarkEdmondson1234** [comment]
I think this is fixed now from my local tests
