### ISSUE TITLE
Problem with the yt_auth()

### ISSUE THREAD

**Issue by Aquamanouche** [MarkEdmondson1234/youtubeAnalyticsR#5]
Hi Mark, hi github community,

It's strange for me to write an issue here, since a long time I use your Google Analitycs API (and it's absolutely wonderful). 
So, thank you for everything you did.

It was such a pleasure when I discovered this package. (I hate [Google API](https://developers.google.com/youtube/analytics/metrics) so much)

I saw an [issue](https://github.com/MarkEdmondson1234/googleAuthR/issues/108) there's a long time ago about the scope and the authentification problem (`gar_auto_auth()`). 
It works as well when I create a token with `gar_auth()`, then it works when I use `ga_auth("MY .OAUTH PATH")` and it perfectly corrected my issue.

It seems that it's impossible to do the same thing with `yt_auth()` (the "`token`" parameter doesn't exist).
So, i did that : 
```
options(googleAuthR.client_id = 'MY ID')
options(googleAuthR.client_secret = 'MY SECRET ID')
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

library(youtubeAnalyticsR)

yt_auth()
```

With this strange result : 
`No environment argument found, looked in YT_AUTH_FILE`

And then 
`yt_auth()`

> Error in googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :    
> Cannot authenticate - options(googleAuthR.scopes.selected) needs to be set to includehttps://www.googleapis.com/auth/youtube or https://www.googleapis.com/auth/youtube.readonly or https://www.googleapis.com/auth/yt-analytics-monetary.readonly or https://www.googleapis.com/auth/yt-analytics.readonly

Have you got an idea to help me ?
I know that this is a Beta Package but I have the impression that this is a simple problem :'(

I use MRO 3.5.1, I installed your package with `devtools::install_github("MarkEdmondson1234/youtubeAnalyticsR")`.

Thank so much, Ugo.

**Comment by MarkEdmondson1234** [comment]
Hi Ugo, thanks for your kind message. 

I think you are nearly there, you only need to change the scopes in the options to those suggested in the error message - at the moment you are against cloud-platform which only works for BigQuery/Cloud storage services etc.

**Comment by Aquamanouche** [comment]
Yeah !!

Thank you for your answer, it's perfect.
I folowed [Google's Doc](https://developers.google.com/youtube/v3/guides/auth/installed-apps#identify-access-scopes) to find a scope.
It's actually hard to choose, i tried [readonly](https://www.googleapis.com/auth/youtube.readonly).

Thank you again, for all the packages you've done. It works great :)
Have a nice day, Ugo. (And happy new year 2019)
