### ISSUE TITLE
Package not available

### ISSUE THREAD

**Issue by ArbenKqiku** [MarkEdmondson1234/youtubeAnalyticsR#7]
Hey Mark,

When I try to run the following code:

install.packages('youtubeAnalyticsR')

library(youtubeAnalyticsR)

I get this message:

Warning in install.packages :
  package ‘youtubeAnalyticsR’ is not available (for R version 3.4.2)

I have the latest version of R. Do you know where the problem lies by any chance?

Thank you.

Arben

**Comment by MarkEdmondson1234** [comment]
Its not available on CRAN, you need to install from GitHub :) 

```r
remotes::install_github("MarkEdmondson1234/youtubeAnalyticsR")
```

**Comment by ArbenKqiku** [comment]
Thanks man, it worked! :)
